[package]
name = "buildpack-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_toml = "0.22.1"
libcnb = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
toml = "0.8.22"
ureq = "3.0.11"
