name: Build, Test, Publish

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

env:
  BUILDPACK_NAME: buildpack-rust

jobs:
  create:
    strategy:
      fail-fast: false
      matrix:
        build: 
          - arch: "amd64"
            target: x86_64-unknown-linux-musl 
          - arch: "arm64"
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.build.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@c502bcff683efa6f6d56a325df3fbe1722e21881 # v5.8.11

      - name: Install musl tools
        run: sudo apt install -y musl-tools

      - name: Add rust target
        run: rustup target add ${{ matrix.build.target }}

      - name: Install libcnb-cargo
        run: cargo install --locked libcnb-cargo

      - name: Create builder image
        run: cargo libcnb package --release --target ${{ matrix.build.target }}

      - name: Publish Docker images
        run: |
          pack buildpack package ${{ env.BUILDPACK_NAME }} \
            --path packaged/${{ matrix.build.target }}/kea-run_${{ env.BUILDPACK_NAME }}/release
          


