name: Build, Test, Publish

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

env:
  BUILDPACK_NAME: ${{ github.repository.name }}
  REGISTRY: ghcr.io/kea-run

jobs:
  create:
    strategy:
      matrix:
        build: 
          - arch: "amd64"
            target: x86_64-unknown-linux-musl 
          - arch: "arm64"
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.build.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    outputs:
      image_name: ${{ steps.image_info.outputs.image_name }}
    env:
      BUILDPACK_PATH: packaged/${{ matrix.build.target }}/release/kea-run_${{ github.event.repository.name }}
      IMAGE_TAG: ${{ matrix.build.arch }}-${{ github.run_number }} 
      IMAGE_NAME: ${{ github.event.repository.name }}:${{ matrix.build.arch }}-${{ github.run_number }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@c502bcff683efa6f6d56a325df3fbe1722e21881 # v5.8.11

      - name: Install musl tools
        run: sudo apt install -y musl-tools

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/crates.toml
            target/
          key: cargo-${{ runner.os }}-${{ matrix.build.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Add rust target
        run: rustup target add ${{ matrix.build.target }}

      - name: Install libcnb-cargo
        run: cargo install --locked libcnb-cargo --force

      - name: Create builder image
        run: cargo libcnb package --release --target ${{ matrix.build.target }}

      - name: Create Docker images
        run: |
          cat $BUILDPACK_PATH/buildpack.toml

          pack buildpack package ${{ env.IMAGE_NAME }} \
            --target "linux/${{ matrix.build.arch }}" \
            --path $BUILDPACK_PATH
        
      - name: Export Docker images from the Docker daemon
        id: docker_save
        # Using sed rather than yq until this yq bug is fixed:
        # https://github.com/mikefarah/yq/issues/1758
        run: |
          docker_archive="${{ env.BUILDPACK_NAME}}_${{ matrix.build.arch }}.tar.zst"
          docker save ${{ env.IMAGE_NAME }} | zstd -T0 --long=31 -o $docker_archive
          
          echo "saved ${{ env.IMAGE_NAME }} to $docker_archive"

          echo "docker_archive=$docker_archive" >> "$GITHUB_OUTPUT"


      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILDPACK_NAME}}-${{ matrix.build.arch }}
          path: ${{ steps.docker_save.outputs.docker_archive }}


  push:
    strategy:
      matrix:
        container_registry: 
          - registry: ghcr.io/${{ github.repository_owner }} 
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: [create]
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Download image artifacts
        uses: actions/download-artifact@v4
        with:
          path: images

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ matrix.container_registry.registry }}
          username: ${{ matrix.container_registry.username }}
          password: ${{ matrix.container_registry.password }}
      - name: Load and push docker images
        id: images
        run: |
          ls -la ./images
        
          docker_args=""

          for f in $(find ./images -maxdepth 2 -type f); do
              basename="$(basename $f)"
              echo "Loading $f into docker"
              zstd -dc --long=31 $f | docker load

              filename="${basename%.*.*}"
              IFS=_ read -r image tag <<< $filename
              echo "got image: $image, tag: $tag from $f"
              
              image_name="${{ matrix.container_registry.registry }}/$image:$tag"

              docker tag $image:$tag-${{ github.run_number }} $image_name 
              echo "Pushing $image_name"
              docker push $image_name

              docker_args=" --amend $image_name $docker_args"

          done
      
          echo "docker_args=$docker_args" >> "$GITHUB_OUTPUT"


      - name: Create and push docker manifest
        run: |
          docker manifest create \
            ${{ matrix.container_registry.registry }}/${{ env.BUILDPACK_NAME }}:latest \
            ${{ steps.images.outputs.docker_args }}


            docker manifest push ${{ matrix.container_registry.registry }}/${{ env.BUILDPACK_NAME }}:latest
